image: mcr.microsoft.com/dotnet/core/sdk:3.1


stages: 
    - build 
    - test

    # install dependencies, react and node
    before_script:
        - dotnet restore
        - dotnet --info
        - curl -sL https://deb.nodesource.com/setup_10.x | bash -
        - apt-get install -y nodejs
        - npm install -g react
    

build:
    stage: build
    script:
        - dotnet build

test:
    stage: test
    script:
        - dotnet test