image: docker:stable

stages: 
    - build 
    - test
    - deploy

services:
    - docker:dind

before_script:
    - docker info


#     # install dependencies, react and node
# before_script:
#     - dotnet restore
#     - dotnet --info
#     - curl -sL https://deb.nodesource.com/setup_10.x | bash -
#     - apt-get install -y nodejs
#     - npm install -g react


build_and_push_to_GitlabRegsitry:
    only: 
    master
    stage: build
    before_script:
        - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    script:
        - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
        - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
    after_script:
        - docker logout ${CI_REGISTRY)}
    tags:
        - docker

