image: mcr.microsoft.com/dotnet/core/sdk:3.1


stages: 
    - build 
    - test
    - deploy

    # install dependencies, react and node
before_script:
    - dotnet restore
    - dotnet --info
    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - apt-get install -y nodejs
    - npm install -g react


build:
    stage: build
    script:
        - dotnet build

test:
    stage: test
    script:
        - dotnet test

deploy_to_production:
    stage: deploy
    image: ruby:latest
    script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=homehealth876 --api-key=$HEROKU_API_KEY
    only:
    - master
          
          