# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: "windows-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  repositoryname: "homehealth-api"
  tag: "$(Build.BuildId)"

steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: "$(solution)"


  - task: VSTest@2
    inputs:
      platform: "$(buildPlatform)"
      configuration: "$(buildConfiguration)"

  # Run tests and auto publish test results.
  - task: DotNetCoreCLI@2
    inputs:
      command: "test"
      arguments: '--collect "Code coverage"'
      projects: "**/*.test.csproj"
      testRunTitle: "Home Health API Tests"
      workingDirectory: "$(System.DefaultWorkingDirectory)/HomeHealth.Test"

  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'appsettings.Production.json'
    
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.WorkFolder)\_temp'
      Contents: 'appsettings.Production.json'
      TargetFolder: '$(System.DefaultWorkingDirectory)/HomeHealth.Web'

  - task: DotNetCoreCLI@2
    inputs:
      command: "publish"
      publishWebProjects: true
      arguments: "-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)"
      workingDirectory: "$(System.DefaultWorkingDirectory)/HomeHealth.Web"
      zipAfterPublish: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "HomeHealthApi-$(envi)-$(Build.BuildId)"
