version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
    mail:
        image: jeanberu/mailcatcher
        ports:
            - "1025:1025"
            - "1080:1080"
            

